version: '3.7'
services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:alpine3.11
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@host.docker.internal:5435/smart-brain-docker
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: host.docker.internal
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/smart-brain-api
    # network_mode: "host"

  # Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres

  #Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
